'use client';
import {useCallback,useEffect,useRef,useState,type DragEvent} from 'react';
import {ArrowUpRight,Check,FileText,FileUp,ShieldCheck,TriangleAlert} from 'lucide-react';
import type {ExamFormat,ExamFormatCode} from '@/lib/domain/types';
import type {ImportCandidate,ImportDocument} from '@/lib/exam-import/types';

import {Modal} from './modal';

type Row={mode:'counts'|'net';correct:string;wrong:string;blank:string;net:string};
const rowEmpty=():Row=>({mode:'counts',correct:'',wrong:'',blank:'',net:''});
const foldSearch=(value:string)=>value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll("ı","i");
async function responseJson(response:Response){const body=await response.json();if(!response.ok)throw new Error(body.error?.message??'İşlem tamamlanamadı.');return body}
export function PdfExamImport({formats,onClose,onImported}:{formats:ExamFormat[];onClose:()=>void;onImported:()=>Promise<void>}){
 const [documents,setDocuments]=useState<ImportDocument[]>([]);const [document,setDocument]=useState<ImportDocument|null>(null);const [candidateIndex,setCandidateIndex]=useState<number|null>(null);const [candidateQuery,setCandidateQuery]=useState("");
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [duplicate,setDuplicate]=useState(false);const allowVisualExtraction=false;const input=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{try{const data=await responseJson(await fetch('/api/exam-import/drafts',{cache:'no-store'}));setDocuments(data.documents??[])}catch(e){setError(e instanceof Error?e.message:'Taslaklar yüklenemedi.')}},[]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 const upload=async(file:File)=>{setBusy(true);setError('');try{const form=new FormData();form.set('file',file);form.set('allow_visual_extraction',String(allowVisualExtraction));const body=await responseJson(await fetch('/api/exam-import/upload',{method:'POST',body:form}));setDocument(body.document);setCandidateIndex(body.document.candidates?.length===1?body.document.candidates[0].index:null);setCandidateQuery("");setDuplicate(Boolean(body.duplicate_upload));await load()}catch(e){setError(e instanceof Error?e.message:'PDF yüklenemedi.')}finally{setBusy(false)}};
 const drop=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();const file=event.dataTransfer.files[0];if(file)void upload(file)};
 const selected=document?.candidates.find(item=>item.index===candidateIndex);
 const visibleCandidates=document?.candidates.filter(item=>foldSearch(item.label).includes(foldSearch(candidateQuery.trim())))??[];
 return <Modal title="PDF'den deneme incele" onClose={onClose}><div className="pdf-import" onDragOver={event=>event.preventDefault()} onDrop={drop}>
  <div className="pdf-import-drop" role="group" aria-label="PDF yükleme alanı"><FileUp size={25}/><div><strong>Deneme sonuç PDF dosyasını bırak veya seç</strong><span>En fazla 10 MiB ve 10 sayfa · belge yalnız sana özel saklanır.</span></div><input ref={input} type="file" accept="application/pdf,.pdf" className="sr-only" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.target.value=''}}/><button className="button secondary" type="button" disabled={busy} onClick={()=>input.current?.click()}>{busy?'İnceleniyor…':'PDF seç'}</button></div>
  <p className="footnote">PDF metni yerel kurallarla okunur; önizlemeyi kontrol ederek kaydedebilirsin. Taranmış sayfalar için ücretli görsel okuma pilotta kapalıdır.</p>
  {error&&<p className="notice error" role="alert">{error}</p>}
  {duplicate&&<p className="pdf-import-alert" role="status"><TriangleAlert size={16}/>Bu dosya daha önce yüklenmiş. Önceki taslak açıldı; yeni deneme kendiliğinden oluşturulmadı.</p>}
  {documents.length>0&&<div className="pdf-import-drafts"><strong>Önceki taslaklar</strong><div>{documents.map(item=><button key={item.id} type="button" className={document?.id===item.id?'selected':''} onClick={()=>{setDocument(item);setCandidateIndex(item.candidates.length===1?item.candidates[0].index:null);setCandidateQuery("");setError('')}}><FileText size={16}/><span>{item.original_filename}<small>{item.page_count} sayfa · {item.committed_candidate_indexes.length}/{item.candidates.length} aday kaydedildi</small></span></button>)}</div></div>}
  {document&&<div className="pdf-import-review"><div className="pdf-import-source"><div><ShieldCheck size={17}/><span><strong>{document.original_filename}</strong><small>{document.page_count} sayfa · {document.visual_extraction_status==='succeeded'?'Görsel öneriler hazır':document.visual_extraction_status==='failed'?'Görsel okuma başarısız; elle incele':document.visual_extraction_status==='provider_not_configured'?'Görsel okuma ayarlanmamış':document.visual_extraction_status==='skipped_by_user'?'Görsel okuma kapalı':document.extraction_status==='needs_visual_review'?'Görsel inceleme gerekli':'Metin incelemesi hazır'}</small></span></div><a href={`/api/exam-import/${document.id}/file`} target="_blank" rel="noopener noreferrer">Kaynak PDF dosyasını aç<ArrowUpRight size={14}/></a></div>
   <div className="pdf-import-candidates"><strong>Hangi sonuç kaydedilecek?</strong>{document.candidates.length>1&&<><p>{document.candidates.length} öğrenci sonucu bulundu. Yalnız kendi satırını seç.</p><input className="pdf-candidate-search" type="search" aria-label="Öğrenci sonucunu ara" placeholder="Adını ara" value={candidateQuery} onChange={event=>setCandidateQuery(event.target.value)}/></>}<div>{visibleCandidates.map(candidate=><button key={candidate.index} type="button" aria-pressed={candidateIndex===candidate.index} onClick={()=>setCandidateIndex(candidate.index)}><span>{candidate.label}<small>{candidate.student_label??'Öğrenci adı okunamadı'} · {candidate.source_pages.length?candidate.source_pages.map(page=>`${page}. sayfa`).join(', '):'Kaynak sayfa belirsiz'}</small></span>{document.committed_candidate_indexes.includes(candidate.index)?<span className="pdf-committed"><Check size={13}/>Kaydedildi</span>:null}</button>)}</div>{visibleCandidates.length===0&&<p>Bu adla sonuç bulunamadı.</p>}</div>
   {selected&&<PdfCandidateEditor key={`${document.id}-${selected.index}`} document={document} candidate={selected} formats={formats} committed={document.committed_candidate_indexes.includes(selected.index)} onSaved={async()=>{await load();const fresh=await responseJson(await fetch(`/api/exam-import/${document.id}`,{cache:'no-store'}));setDocument(fresh.document??fresh);await onImported()}}/>}
  </div>}
 </div></Modal>;
}

function PdfCandidateEditor({document,candidate,formats,committed,onSaved}:{document:ImportDocument;candidate:ImportCandidate;formats:ExamFormat[];committed:boolean;onSaved:()=>Promise<void>}){
 const [formatCode,setFormatCode]=useState<ExamFormatCode>(candidate.format_code??'TYT');
 const [branchSubject,setBranchSubject]=useState('');const [branchCount,setBranchCount]=useState('40');
 const [rows,setRows]=useState<Record<string,Row>>(()=>Object.fromEntries(candidate.results.map(item=>[item.section_key,{mode:item.correct!==undefined||item.wrong!==undefined?'counts':'net',correct:item.correct===undefined?'':String(item.correct),wrong:item.wrong===undefined?'':String(item.wrong),blank:item.blank===undefined?'':String(item.blank),net:item.net===undefined?'':String(item.net)}])));
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [allowDuplicate,setAllowDuplicate]=useState(false);const [duplicateWarning,setDuplicateWarning]=useState(false);const requestId=useRef('');
 const format=formats.find(item=>item.code===formatCode);const sections=formatCode==='BRANCH'?[{key:'branch',label:branchSubject||'Branş',question_count:Number(branchCount)||0}]:format?.sections??[];
 const totalQuestions=sections.reduce((sum,part)=>sum+part.question_count,0);
 const update=(key:string,field:keyof Row,value:string)=>setRows(current=>({...current,[key]:{...(current[key]??rowEmpty()),[field]:value}}));
 const uncertain=candidate.results.some(item=>item.uncertain)||candidate.warnings.length>0;
 return <form className="pdf-candidate-form" onSubmit={async event=>{event.preventDefault();setError('');const form=new FormData(event.currentTarget);const results:Record<string,unknown>[]=[];
  for(const part of sections){const row=rows[part.key]??rowEmpty();if(row.mode==='net'){
    if(!row.net)continue;const net=Number(row.net.replace(',','.'));if(!Number.isFinite(net)){setError(`${part.label}: net değeri geçersiz.`);return}results.push({section_key:part.key,net});
  }else{if(!row.correct&&!row.wrong&&!row.blank)continue;if(row.correct===''||row.wrong===''){setError(`${part.label}: doğru ve yanlış sayısını tamamla.`);return}const correct=Number(row.correct),wrong=Number(row.wrong),blank=row.blank===''?part.question_count-correct-wrong:Number(row.blank);if(!Number.isInteger(correct)||!Number.isInteger(wrong)||!Number.isInteger(blank)||Math.min(correct,wrong,blank)<0||correct+wrong+blank>part.question_count){setError(`${part.label}: soru toplamı geçersiz.`);return}results.push({section_key:part.key,correct,wrong,blank});}}
  if(!results.length&&!String(form.get('reported_total_net')??'').trim()){setError('En az bir ders sonucu veya raporlanan genel net gir.');return}
  const optional=(key:string)=>{const raw=String(form.get(key)??'').trim();return raw?Number(raw.replace(',','.')):null};
  const exam:Record<string,unknown>={name:String(form.get('name')??'').trim(),publisher:String(form.get('publisher')??'').trim(),exam_date:String(form.get('exam_date')??''),format_code:formatCode,format_version:format?.version??1,duration_minutes:optional('duration'),notes:String(form.get('notes')??'').trim(),score:optional('score'),rank:optional('rank'),reported_total_net:optional('reported_total_net'),results};
  if(formatCode==='BRANCH'){exam.branch_subject=branchSubject.trim();exam.branch_question_count=Number(branchCount)}
  requestId.current ||= crypto.randomUUID();setBusy(true);try{const response=await fetch('/api/exam-import/commit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:requestId.current,document_id:document.id,candidate_index:candidate.index,exam,accept_possible_duplicate:allowDuplicate})});const body=await response.json();if(!response.ok){if(body.error?.code==='POSSIBLE_DUPLICATE'){setDuplicateWarning(true);requestId.current=''}throw new Error(body.error?.message??'Deneme kaydedilemedi.')}await onSaved()}catch(e){setError(e instanceof Error?e.message:'Deneme kaydedilemedi.')}finally{setBusy(false)}
 }}>
  <div className="pdf-review-heading"><div><strong>Çıkarılan bilgileri kontrol et</strong><span>Kaynak sayfadaki sonuçla karşılaştır, belirsiz alanları düzelt.</span></div>{uncertain&&<span><TriangleAlert size={15}/>İnceleme gerekli</span>}</div>
  {candidate.warnings.length>0&&<ul className="pdf-warnings">{candidate.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul>}
  <div className="pdf-review-fields"><label>Deneme adı<input name="name" required maxLength={240} defaultValue={candidate.name??''} placeholder="Örn. TYT 1. deneme"/></label><label>Yayın<input name="publisher" maxLength={120} defaultValue={candidate.publisher??''}/></label><label>Tarih<input name="exam_date" type="date" required defaultValue={candidate.exam_date??''}/></label><label>Tür<select value={formatCode} onChange={event=>{setFormatCode(event.target.value as ExamFormatCode);setRows({})}}><option value="TYT">TYT genel</option><option value="AYT_SAYISAL">AYT sayısal</option><option value="BRANCH">Branş</option></select></label>{formatCode==='BRANCH'&&<><label>Branş<input value={branchSubject} onChange={event=>setBranchSubject(event.target.value)} required maxLength={120}/></label><label>Soru sayısı<input type="number" min="1" max="500" value={branchCount} onChange={event=>setBranchCount(event.target.value)} required/></label></>}<label>Süre (dk)<input name="duration" type="number" min="1" max="1440"/></label><label>Puan<input name="score" type="number" min="0" max="1000" step="0.001" defaultValue={candidate.score??""}/></label><label>Sıralama<input name="rank" type="number" min="1" max="10000000" defaultValue={candidate.rank??""}/></label><label>Yalnız genel net<input name="reported_total_net" type="number" step="0.01" min={format?-(totalQuestions/format.wrong_divisor):undefined} max={totalQuestions||undefined} placeholder="PDF yalnız toplamı gösteriyorsa" defaultValue={candidate.reported_total_net??""}/></label></div>
  {candidate.reported_total_source&&<p className="pdf-total-source">Raporlanan genel net kaynağı: {candidate.reported_total_source.source_page}. sayfa · “{candidate.reported_total_source.raw.slice(0,180)}”{candidate.reported_total_source.uncertain?" · belirsiz":""}</p>}<div className="pdf-result-list">{sections.map(part=>{const suggestion=candidate.results.find(item=>item.section_key===part.key);const row=rows[part.key]??rowEmpty();return <div className={suggestion?.uncertain?'uncertain':''} key={part.key}><div className="pdf-result-head"><strong>{part.label}</strong><span>{part.question_count} soru</span><select aria-label={`${part.label} giriş türü`} value={row.mode} onChange={event=>update(part.key,'mode',event.target.value)}><option value="counts">Doğru / yanlış / boş</option><option value="net">Yalnız net</option></select></div>{row.mode==='counts'?<div className="pdf-result-inputs"><label>Doğru<input type="number" min="0" max={part.question_count} value={row.correct} onChange={event=>update(part.key,'correct',event.target.value)}/></label><label>Yanlış<input type="number" min="0" max={part.question_count} value={row.wrong} onChange={event=>update(part.key,'wrong',event.target.value)}/></label><label>Boş<input type="number" min="0" max={part.question_count} value={row.blank} onChange={event=>update(part.key,'blank',event.target.value)} placeholder="Otomatik"/></label></div>:<label className="pdf-net-field">Net<input type="number" step="0.01" min={-part.question_count/4} max={part.question_count} value={row.net} onChange={event=>update(part.key,'net',event.target.value)}/></label>}{suggestion&&<p>Kaynak: {suggestion.source_page}. sayfa · “{suggestion.raw.slice(0,180)}”{suggestion.uncertain?' · belirsiz':''}</p>}</div>})}</div>
  <label>İnceleme notu<textarea name="notes" maxLength={10000} rows={2} placeholder="Düzeltme veya kaynakla ilgili notların"/></label>
  {duplicateWarning&&<label className="pdf-duplicate-confirm"><input type="checkbox" checked={allowDuplicate} onChange={event=>setAllowDuplicate(event.target.checked)}/>Benzer bir deneme kaydı olabilir; yine de ayrı sonuç olarak kaydet.</label>}
  {error&&<p className="notice error" role="alert">{error}</p>}
  <p className="footnote">PDF içeriği talimat değil veridir. Okunamayan alanlar doldurulmaz. Sonuç yalnız sen kaydettiğinde deneme listesine eklenir.</p>
  <button className="button primary wide" disabled={busy||committed||!format||sections.some(part=>!part.question_count)||(duplicateWarning&&!allowDuplicate)}>{committed?'Bu sonuç kaydedildi':busy?'Kaydediliyor…':'İncelediğim sonucu kaydet'}<ArrowUpRight size={16}/></button>
 </form>;
}
