'use client';
import {useState,type CSSProperties} from 'react';
import {Check,Monitor,Moon,Sun,ShieldCheck,LogOut} from 'lucide-react';
import type {AppState} from '@/lib/domain/types';
import {themes,type CommandFn} from '@/lib/ui';
import {Card} from './primitives';
import {GoogleCalendarSettings} from './google-calendar-settings';
export function Preferences({state,command,busy,theme,appearance,reduced,simple,setTheme,setAppearance,setReduced,setSimple,initialTab='appearance'}:{state:AppState;initialTab?:'appearance'|'plan'|'connections';command:CommandFn;busy:boolean;theme:string;appearance:string;reduced:boolean;simple:boolean;setTheme:(v:string)=>void;setAppearance:(v:string)=>void;setReduced:(v:boolean)=>void;setSimple:(v:boolean)=>void}){
 const [tab,setTab]=useState<'appearance'|'plan'|'connections'|'account'>(initialTab);
 const [notice,setNotice]=useState('');
 const settings=state.settings;
 const yks=state.education?.profile?.yks_goal??true;
 const fixedBase=theme==='white'||theme==='black';
 return <>
 <div className="settings-tabs">{[['appearance','Görünüm'],['plan','Plan ve hedefler'],['connections','Bağlantılar'],['account','Hesap']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as 'appearance'|'plan'|'connections'|'account')}>{label}</button>)}</div>
 {notice&&<p className="notice" role="status">{notice}</p>}
 {tab==='appearance'&&<><Card title="Sana iyi gelen renkler" eyebrow="TEMA"><p className="soft-copy">Sakin zeminler, birbirini tamamlayan canlı renkler. Çalışma alanını sana iyi gelen paletle kişiselleştir.</p><div className="theme-grid">{themes.map(t=><button key={t.id} className={'theme-card '+(theme===t.id?'selected':'')} aria-label={t.name} aria-describedby={'theme-pair-'+t.id} aria-pressed={theme===t.id} onClick={()=>setTheme(t.id)}><div className="theme-preview palette-preview contrast-preview" data-palette={t.id} aria-hidden="true" style={{'--preview-primary':t.accents[0],'--preview-accent':t.accents[1],'--preview-background':t.id==='black'?'#121316':t.id==='white'?'#f3f4f6':`color-mix(in srgb, ${t.colors.at(-1)} 20%, #f4f5f6)`,'--preview-surface':t.id==='black'?'#24262c':'#ffffff',background:'var(--preview-background)'} as CSSProperties}><div className="palette-mini-copy"><span className="palette-mini-line"/><span className="palette-mini-line"/><span className="palette-mini-accent" style={{background:`linear-gradient(160deg, ${t.accents[0]}, ${t.accents[1]})`}}/></div><div className="palette-mini-ring" style={{background:`conic-gradient(${t.accents[0]} 0 60%,${t.accents[1]} 60% 100%)`}}><i style={{background:'var(--preview-surface)'}}/></div><div className="theme-palette">{t.colors.map(color=><span key={color} style={{background:color}}/>)}</div></div><strong>{t.name}{theme===t.id&&<Check size={16}/>}</strong><small className="theme-pair" id={'theme-pair-'+t.id}>{t.pair}</small></button>)}</div><div className="card-bottom"><span>Tema bu cihazda hemen uygulanır.</span><button className="button primary" disabled={busy||!state.authenticated} onClick={async()=>{if(await command('settings.update',{expected_revision:settings?.revision??0,theme,reduced_motion:reduced,simple_view:simple}))setNotice('Görünüm hesabına kaydedildi.')}}>Hesabımla eşitle</button></div></Card>
 <Card title="Görünüm tercihleri"><div className="setting-row"><div><h3>Renk modu</h3><p>{fixedBase?'Bu temanın zemin rengi sabittir. Diğer temalar için renk modu tercihin korunur.':'Bu cihaz için saklanır.'}</p></div>{fixedBase?<span className="pill fixed-base-label">{theme==='black'?<Moon size={16}/>:<Sun size={16}/>} Sabit {theme==='black'?'siyah':'beyaz'} zemin</span>:<div className="segmented">{[['dark','Koyu',Moon],['light','Açık',Sun],['system','Sistem',Monitor]].map(([id,label,Icon])=><button key={id as string} aria-pressed={appearance===id} onClick={()=>setAppearance(id as string)}>{typeof Icon!=='string'&&<Icon size={16}/>} {label as string}</button>)}</div>}</div><label className="setting-row"><div><h3>Az hareket</h3><p>Geçiş ve animasyonları azalt.</p></div><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/></label><label className="setting-row"><div><h3>Sade görünüm</h3><p>Dekoratif ayrıntıları azalt.</p></div><input type="checkbox" checked={simple} onChange={e=>setSimple(e.target.checked)}/></label></Card></>}
 {tab==='plan'&&<Card title="Plan ve hedefler"><form key={settings?.revision??0} className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await command('settings.update',{expected_revision:settings?.revision??0,display_name:f.get('display_name'),...(yks?{exam_year:Number(f.get('exam_year')),exam_date:f.get('exam_date')||null,target_rank:f.get('target_rank')?Number(f.get('target_rank')):null}:{}),daily_target_minutes:Number(f.get('daily_target_minutes')),weekday_targets:Array.from({length:7},(_,i)=>Number(f.get('day'+i)))})}}>
 <label>Adın<input name="display_name" required defaultValue={settings?.display_name??''} placeholder="Adın"/></label>{yks&&<><label>Sınav yılı<input type="number" name="exam_year" min="2020" max="2100" required defaultValue={settings?.exam_year??new Date().getFullYear()}/></label><label>Hedef sıralama<input type="number" name="target_rank" min="1" defaultValue={settings?.target_rank??''} placeholder="İsteğe bağlı"/></label><label>Sınav tarihi<input type="date" name="exam_date" defaultValue={settings?.exam_date??''}/><small>Hedeflediğin sınavın tarihini buradan ayarlayabilirsin.</small></label></>}<label>Varsayılan günlük hedef (dk)<input type="number" min="0" max="1440" required name="daily_target_minutes" defaultValue={settings?.daily_target_minutes??360} onChange={e=>{const form=e.currentTarget.form;for(let i=0;i<7;i++){const input=form?.elements.namedItem('day'+i) as HTMLInputElement|null;if(input)input.value=e.currentTarget.value}}}/><small>Değiştirince hafta günleri de bu hedefe ayarlanır; aşağıdan farklılaştırabilirsin.</small></label>
 <fieldset className="span-2"><legend>Haftanın günleri için hedef (dakika)</legend><div className="week-targets">{['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].map((day,i)=><label key={day}>{day}<input name={'day'+i} type="number" min="0" max="1440" required defaultValue={settings?.weekday_targets[i]??360}/></label>)}</div></fieldset>
 <p className="footnote span-2">Sıfır süre hedefi “tanımlı değil” olarak işlenir. Plan değişiklikleri sürümlenir; geçmiş günler yeni varsayılanlarla yeniden yazılmaz.</p>
 <div className="form-actions span-2"><button className="button primary" disabled={busy||!state.authenticated}>Hedefleri kaydet</button></div></form></Card>}
 {tab==='connections'&&<div className="integration-grid"><GoogleCalendarSettings authenticated={state.authenticated}/></div>}
 {tab==='account'&&<><Card title="Kişisel hesap" action={<ShieldCheck size={22}/>}><p className="soft-copy">{state.authenticated?'Hesabınla giriş yaptın. Planların, çalışma kayıtların ve denemelerin bu hesaba bağlı saklanır. Öğretmenin olmasa da çalışma alanını kullanabilirsin.':'Çalışmalarını hesabına kaydetmek için giriş yap veya bireysel öğrenci hesabı oluştur.'}</p><p className="footnote"><a href="/classroom">Hesap ve sınıf durumunu gör</a> · <a href="/forgot-password">Şifremi unuttum</a></p>{state.authenticated&&<button className="button secondary" onClick={async()=>{try{const response=await fetch('/api/logout',{method:'POST'});if(!response.ok){const data=await response.json();setNotice(data.error?.message??'Çıkış yapılamadı.');return}location.reload()}catch{setNotice('Bağlantı kurulamadı; çıkış tamamlanmadı.')}}}><LogOut size={17}/>Çıkış yap</button>}</Card><Card title="Cihazına kur"><p className="soft-copy">Tarayıcının menüsündeki “Uygulamayı yükle” veya “Ana ekrana ekle” seçeneğiyle YKSim’e daha hızlı ulaşabilirsin.</p><p className="footnote">Kayıtlarını görüntülemek ve kaydetmek için internet bağlantısı gerekir.</p></Card></>}
 </>;
}


