'use client';
import {useState} from 'react';
import {Check,Clock3,ListTodo,MoreHorizontal,Play,Plus,ArrowUp,ArrowDown,Trash2} from 'lucide-react';
import type {AppState,Task} from '@/lib/domain/types';
import {formatDay,localDate,studyTypes,type CommandFn} from '@/lib/ui';
import {Card,Empty,AddButton} from './primitives';
import {Modal} from './modal';
import {CourseSelector} from './course-selector';
export function Tasks({state,command,busy,requestNew,onNewHandled}:{state:AppState;command:CommandFn;busy:boolean;requestNew:boolean;onNewHandled:()=>void}){
 const [selectedDate,setSelectedDate]=useState<string|null>(null);const [filter,setFilter]=useState('all');const [draft,setDraft]=useState<Task|null|false>(false);const [deleting,setDeleting]=useState<Task|null>(null);
 const today=localDate(new Date(),state.settings?.timezone);const date=selectedDate??today;
 const dailyTasks=state.tasks.filter(t=>t.plan_date===date);
 const overdueTasks=date===today&&filter!=='done'?state.tasks.filter(t=>t.plan_date<today&&t.progress<1).sort((a,b)=>a.plan_date.localeCompare(b.plan_date)||a.position-b.position):[];
 const tasks=[...overdueTasks,...dailyTasks.filter(t=>filter==='all'||(filter==='done'?t.progress===1:t.progress<1)).sort((a,b)=>a.position-b.position)];
 const close=()=>{setDraft(false);onNewHandled()};
 return <>
 <div className="toolbar"><div className="toolbar-group"><label className="inline-label">Plan tarihi<input type="date" value={date} onChange={e=>setSelectedDate(e.target.value===today?null:e.target.value)}/></label><select aria-label="Görev durumu" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tüm görevler</option><option value="open">Devam edenler</option><option value="done">Tamamlananlar</option></select></div><AddButton onClick={()=>setDraft(null)}/></div>
 <Card className={tasks.length===0?'ambient-card':''} title={date===today?'Bugünün planı':'Günlük plan'} action={<span className="pill">{tasks.length} görev</span>}>
 {tasks.length===0?<Empty icon={<ListTodo size={30}/>} title={dailyTasks.length?'Bu görünümde görev yok':'Planına yer aç'} text={dailyTasks.length?filter==='done'?'Bu gün için henüz tamamlanan görev yok.':'Bu günün tüm görevleri tamamlandı.':'Bir görev ekle, çalışma süresini belirle ve ilerlemeyi adım adım takip et.'} action={dailyTasks.length?<button className="button secondary" onClick={()=>setFilter('all')}>Tüm görevleri göster</button>:<button className="button secondary" onClick={()=>setDraft(null)}><Plus size={17}/>İlk görevi ekle</button>}/>:<div className="task-list">{tasks.map((task,i)=><article className="task-item" key={task.id}>
 <div className="task-main"><button className={'check-button '+(task.progress===1?'checked':'')} aria-label={task.title+(task.progress===1?' tamamlamasını geri al':' görevini tamamla')} disabled={busy} onClick={()=>void command('task.update',{id:task.id,expected_revision:task.revision,progress:task.progress===1?0:1,steps:task.steps.map(s=>({...s,completed:task.progress!==1}))})}>{task.progress===1?<Check size={15}/>:task.progress>0?<span/>:null}</button><div className="task-description"><div className="task-tags">{task.plan_date<date&&<span className="pill">{formatDay(task.plan_date,{day:'numeric',month:'short'})} tarihinden kaldı</span>}{task.subject&&<span className="pill">{task.exam} {task.subject}</span>}<span>{task.study_type}</span>{task.priority==='high'&&<span className="priority">Öncelikli</span>}</div><h3 className={task.progress===1?'done':''}>{task.title}</h3>{task.resource&&<p>{task.resource}</p>}<div className="task-meta"><span><Clock3 size={14}/>{task.planned_minutes} dk</span><span>{{easy:'Kolay',medium:'Orta',hard:'Zor'}[task.difficulty]}</span><span>%{Math.round(task.progress*100)} tamamlandı</span></div></div><button className="icon-button" aria-label={task.title+' düzenle'} onClick={()=>setDraft(task)}><MoreHorizontal size={20}/></button></div>
 {task.steps.length>0&&<div className="substeps">{task.steps.map(step=><label key={step.id}><input type="checkbox" checked={step.completed} disabled={busy} onChange={e=>void command('task.update',{id:task.id,expected_revision:task.revision,steps:task.steps.map(s=>s.id===step.id?{...s,completed:e.target.checked}:s)})}/>{step.title}</label>)}</div>}
 <div className="task-actions"><div><button className="icon-button" aria-label={task.title+' yukarı taşı'} disabled={busy||filter!=='all'||task.plan_date!==date||i===overdueTasks.length} onClick={()=>void command('task.move',{id:task.id,expected_revision:task.revision,direction:'up'})}><ArrowUp size={16}/></button><button className="icon-button" aria-label={task.title+' aşağı taşı'} disabled={busy||filter!=='all'||task.plan_date!==date||i===tasks.length-1} onClick={()=>void command('task.move',{id:task.id,expected_revision:task.revision,direction:'down'})}><ArrowDown size={16}/></button></div><button className="text-button" disabled={busy||state.sessions.some(s=>s.status!=='finished')} onClick={()=>void command('timer.start',{title:task.title,task_id:task.id,topic_id:task.topic_id,subject:task.subject,...(task.course_id?{course_id:task.course_id}:{}),study_type:task.study_type,mode:'stopwatch',target_seconds:null})}><Play size={15}/>Çalışmaya başla</button></div>
 </article>)}</div>}
 </Card>
 <p className="footnote">Görev tamamlamak konunun öğrenme düzeyini değiştirmez. Alt adımlar varsa her adım eşit pay alır.</p>
 {(requestNew||draft!==false)&&!deleting&&<Modal title={draft?'Görevi düzenle':'Yeni görev'} onClose={close}><TaskForm key={draft?draft.id:'new'} state={state} task={draft||null} busy={busy} onClose={close} onDelete={()=>{if(draft){setDeleting(draft);setDraft(false)}}} onSave={async payload=>{if(await command(draft?'task.update':'task.create',draft?{...payload,id:draft.id,expected_revision:draft.revision}:payload)){if(!draft)setSelectedDate(null);close()}}}/></Modal>}
 {deleting&&<Modal title="Görevi sil" onClose={()=>setDeleting(null)}><p className="task-delete-confirm"><strong>{deleting.title}</strong> görevi planından silinecek. Kaydedilmiş çalışma süreleri korunacak.</p><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setDeleting(null)}>Vazgeç</button><button type="button" className="button primary" disabled={busy} onClick={async()=>{if(await command('task.delete',{id:deleting.id,expected_revision:deleting.revision}))setDeleting(null)}}><Trash2 size={16}/>Görevi sil</button></div></Modal>}
 </>;
}
function TaskForm({state,task,busy,onSave,onClose,onDelete}:{state:AppState;task:Task|null;busy:boolean;onSave:(payload:Record<string,unknown>)=>Promise<void>;onClose:()=>void;onDelete:()=>void}){
 const [topic,setTopic]=useState(task?.topic_id??'');
 const [courseId,setCourseId]=useState(task?.course_id??'');
 const [contextChanged,setContextChanged]=useState(false);
 const modern=Boolean(state.education?.profile);
 const [steps,setSteps]=useState(task?.steps??[]);
 return <form className="form-grid" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);const chosen=state.topics.find(t=>t.id===topic);const course=state.education?.courses.find(item=>item.id===courseId);await onSave({title:form.get('title'),...(!task?{plan_date:localDate(new Date(),state.settings?.timezone)}:{}),topic_id:topic||null,...(modern?{course_id:courseId||null}:{}),exam:modern&&!contextChanged&&task?task.exam:chosen?.exam??course?.exam??null,subject:modern?(!contextChanged&&task?task.subject:chosen?.subject??course?.name??null):chosen?.subject??(String(form.get('subject')||'')||null),planned_minutes:Number(form.get('planned_minutes')),difficulty:task?.difficulty??'medium',notes:form.get('notes')??'',study_type:form.get('study_type'),priority:form.get('priority'),steps})}}>
 <label className="span-2">Görev başlığı<input name="title" required maxLength={240} defaultValue={task?.title} placeholder="Örn. Polinomlar: iki test ve yanlış analizi" autoFocus/></label>
 <label className="span-2">Planlanan net dakika<input type="number" min="0" max="1440" name="planned_minutes" defaultValue={task?.planned_minutes??40} required/></label>
 {modern?<div className="span-2"><CourseSelector state={state} value={courseId} onChange={id=>{setCourseId(id);setTopic('');setContextChanged(true);}} disabled={busy} label="Ders (isteğe bağlı)"/></div>:!topic&&<label className="span-2">Ders (isteğe bağlı)<input name="subject" defaultValue={task?.subject??''} placeholder="Örn. AYT Fizik"/></label>}
 <label>Çalışma türü<select name="study_type" defaultValue={task?.study_type??'Soru çözümü'}>{studyTypes.map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Öncelik<select name="priority" defaultValue={task?.priority??'normal'}><option value="low">Düşük</option><option value="normal">Normal</option><option value="high">Yüksek</option></select></label>
 {task&&<fieldset className="span-2"><legend>Alt adımlar</legend>{steps.map((step,i)=><div className="step-edit" key={step.id}><input aria-label={(i+1)+'. alt adım'} required value={step.title} onChange={e=>setSteps(steps.map(s=>s.id===step.id?{...s,title:e.target.value}:s))}/><button type="button" className="text-button" onClick={()=>setSteps(steps.filter(s=>s.id!==step.id))}>Kaldır</button></div>)}<button type="button" className="text-button" onClick={()=>setSteps([...steps,{id:crypto.randomUUID(),title:'',completed:false}])}><Plus size={15}/>Alt adım ekle</button></fieldset>}
 {task&&<label className="span-2">Notlar<textarea name="notes" rows={3} defaultValue={task.notes}/></label>}
 {!state.authenticated&&<p className="notice span-2">Görevlerini kaydetmek için hesabınla giriş yap.</p>}
 <div className="form-actions span-2">{task&&<button className="text-button task-delete-trigger" type="button" disabled={busy||!state.authenticated} onClick={onDelete}><Trash2 size={15}/>Sil</button>}<button className="button secondary" type="button" onClick={onClose}>Vazgeç</button><button className="button primary" disabled={busy||!state.authenticated}>{busy?'Kaydediliyor…':'Görevi kaydet'}</button></div>
 </form>
}

